// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUiN-FbdZrVopzOhUlZfV_gATJA-BmQU',
    appId: '1:829452924368:web:de06384f1daae25228b5d5',
    messagingSenderId: '829452924368',
    projectId: 'crud-flutter-6918f',
    authDomain: 'crud-flutter-6918f.firebaseapp.com',
    storageBucket: 'crud-flutter-6918f.appspot.com',
    measurementId: 'G-5PL5DSLL8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAruILXaCT6Nt0yHo-0b37xewR72__gq1Y',
    appId: '1:829452924368:android:1deb42e3f4a7cca428b5d5',
    messagingSenderId: '829452924368',
    projectId: 'crud-flutter-6918f',
    storageBucket: 'crud-flutter-6918f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1YiedwM9GsWeRWiH5tpe25vCDCdhiI3o',
    appId: '1:829452924368:ios:8acab0428641704d28b5d5',
    messagingSenderId: '829452924368',
    projectId: 'crud-flutter-6918f',
    storageBucket: 'crud-flutter-6918f.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1YiedwM9GsWeRWiH5tpe25vCDCdhiI3o',
    appId: '1:829452924368:ios:8acab0428641704d28b5d5',
    messagingSenderId: '829452924368',
    projectId: 'crud-flutter-6918f',
    storageBucket: 'crud-flutter-6918f.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADUiN-FbdZrVopzOhUlZfV_gATJA-BmQU',
    appId: '1:829452924368:web:0cf05f11f3982d4228b5d5',
    messagingSenderId: '829452924368',
    projectId: 'crud-flutter-6918f',
    authDomain: 'crud-flutter-6918f.firebaseapp.com',
    storageBucket: 'crud-flutter-6918f.appspot.com',
    measurementId: 'G-J5SS5THFMV',
  );

}